# The URL the site will be built for
base_url = "https://marybokhan.github.io"
generate_rss = true
compile_sass = true

title = "Mary's Blog"
description = "Notes about iOS development"
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Mary"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/resume", name = "Resume"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://github.com/marybokhan", icon="fab fa-github"},
    {url = "https://linkedin.com/in/marybokhan", icon="fab fa-linkedin"}
]
